### PR TITLE
Frontend dev

### PR DESCRIPTION
**Pull request by Wentao-7114**
image
new Feature:
When not logged in, the button will show some words to let you login. If you drag and drop a file, the browser will alert you to login.

### CODE REVIEW

**Comment by Wentao-7114** [comment]
Latest commit before presentation:

Added features:

1. toolbars addded:
image

2.Uploading will give an alert if not logged in

3.File preview has a reasonable size:
image

4. Extract full content can display in markdown format:
image

**Comment by goldmermaid** [comment]
The product tour tag here is a bit different compared with the figma one... Can you revise it?
image
image

**Comment by goldmermaid** [comment]
Can you remove the empty space in the bottom?

image

**Comment by goldmermaid** [comment]
hey @Wentao-7114 , can you resolve the conflict above? or we can't merge into main

**Comment by goldmermaid** [comment]
Can you double check the font size is exactly the same as figma? You can use the tool https://chromewebstore.google.com/detail/fonts-infos/dcmemojljgjdnjfckdmffgkcnooejahg?hl=en to check the font size of a webpage

e.g. "Parse Documents" should be 18px on figma, but yours is 22px.
image

image

**Comment by goldmermaid** [comment]
Also let's add responsive asap since it looks pretty ugly (large white space below the page) now...

image

**Comment by Wentao-7114** [comment]
Added features:
1. Put the K-V extracting result in a table (Charles has checked this)
2. Loading animation while extracting:
image
3. updated extracting K-V post request

Things to do:
1. responsive according to Andy's suggestions
2. update full content extraction post request.

**Comment by Wentao-7114** [comment]
new Features:

**responsive design**:
When the screen width is greater than 768px and below 1450px, the button layout will adjust to fit in a column:
image

When the screen width is greater than 1450px, it will show the same as Figma design:
image


same on the parse document page,, benchmarks are 768px and 1150px:
image
image

I choose the benchmarks based on our fixed font size in Figma.

**Comment by goldmermaid** [comment]
Hey @Wentao-7114 , I left some comments in https://www.notion.so/goldpiggy/Sandbox-New-frontend-TODO-wentao-12ed2ffa6f2f80e9af65f49fb870d038?pvs=4 Can you address the comments?

**Comment by Wentao-7114** [comment]
> Hey @Wentao-7114 , I left some comments in https://www.notion.so/goldpiggy/Sandbox-New-frontend-TODO-wentao-12ed2ffa6f2f80e9af65f49fb870d038?pvs=4 Can you address the comments?

Sure. I will take a look.

**Comment by Wentao-7114** [comment]
Added Features:
1. I have implemented a new way to show our pdf. PDF files should be displayed properly on a computer screen.
2. Fixed font sizes and style align to Figma design.
3. Product Tour position fixed. Tour should appear in reasonable postions, at least for computer users. 

Things to do:
Responsive pages for mobile users , including the new implemented pdf viewer, product tour, and document parsing page.

**Pull request merged**
